pipeline {
    agent any
    environment {
        VERSION="0.1.2"
        VERSION_RC="rc.2"
    }
    stages {
        stage('Audit tools'){
            steps {
                echo "Sprawdzam zależności..."
                sh '''
                    get version
                    docker version
                '''
            }
        }
        stage('Build'){
            steps{
                echo "Building version $VERSION with suffix: ${VERSION_RC}"
            }
        }
        stage('Deploy'){
            steps {
                echo "Deploing $VERIOSN and RC-V $VERSION_RC"
            }
        }
    }
}